/**
 * 常量
 */
export class Constants {
  /**
   * 闪屏页持续时间
   */
  static readonly splashTime: number = 1000
  /**
   * 首页路由
   */
  static readonly pageIndex = 'pages/Index'
  /**
   * 数据库ID
   */
  static readonly storeId = 'store'
  /**
   * 文本源前缀
   */
  static readonly textPrefix = 'source-text-'
  /**
   * 图片源前缀
   */
  static readonly imagePrefix = 'source-image-'
  /**
   * 视频源前缀
   */
  static readonly videoPrefix = 'source-video-'
  /**
   * 文件源前缀
   */
  static readonly filePrefix = 'source-file-'
}